### PR TITLE
Enable source-map-support on Lambdas

### PR DESCRIPTION
**Pull request by Limess**
See the [serverless-webpack example](https://github.com/serverless-heaven/serverless-webpack/blob/21393845fb173a6f806b0bc2bee0be7daf0adc86/examples/babel-webpack-4/.babelrc).

This should help debug errors like these: https://financialtimes.splunkcloud.com/en-US/app/search/search?q=search%20index%3Daws_cloudwatch%20source%3D%2Faws%2Flambda%2Fbiz-ops-runbook-md-prod-releaseLog&display.page.search.mode=fast&dispatch.sample_ratio=1&earliest=1564133640&latest=1564133700&sid=1564135290.1491624

Additionally this enables individually packaged functions in webpack, rather than shipping the source code for all lambdas for each lambda.

### CODE REVIEW

**Comment by Limess** [comment]
This is only necessary when bundling lambda code with webpack. Not 100% sure this will work first time, I had a load of fun trying to get it to work before but I believe there's been a lot of work on the `serverless-webpack` repo since.

**Comment by wheresrhys** [comment]
yeah, but I think using serverless webpack is what we shoudl move all our JSX lambdas over to - the current babelification in most of them is a bit weird

**Comment by Limess** [comment]
Made a few tweaks (broken syntax, forgot you need to explicitly install `source-map-support` as the babel plugin actually just adds an import for that module). 

`make package` now works as expected, separate zips are generated for each lambda, and each lambda source file has a source map line and file 

e.g. 
```
.
└── ingester
    └── src
        ├── formHandler.js
        └── formHandler.js.map
```

where `formHandler.js` has the footer ``//# sourceMappingURL=formHandler.js.map`.

The package step now looks like this:

```
❯ make package
Note — An .env file exists. Its contents have been exported as environment variables.
Serverless: Updating Log Forwarding Resources...
Serverless: Log Forwarding Resources Updated
Serverless: Bundling with Webpack...
   21 modules
   67 modules
   54 modules
   27 modules
   46 modules
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: source-map-support@^0.5.12, hyperons@^1.0.0-beta.2, @financial-times/lambda-logger@^2.0.0, lodash@^4.17.14, @financial-times/s3o-lambda@^2.0.3, http-errors@^1.7.3, @financ
ial-times/biz-ops-schema@^3.21.0, unist-util-select@^2.0.2, unist-builder@^1.0.4, unist-util-visit-parents@^2.1.2, unified@^8.1.0, add-line-numbers@^1.0.1, qs@^6.7.0, strip-html-comments@^1.0.0, remark-parse@^
6.0.3, unified-stream@^1.0.5, mdast-util-heading-range@^2.1.3, remark-stringify@^6.0.4, remark-behead@^2.2.1, isomorphic-fetch@^2.2.1, aws-sdk@^2.491.0, @probot/serverless-lambda@^0.3.0, probot@^9.2.16        
Serverless: Packaging service...

❯ ls -la .serverless
total 67268
drwxrwxrwx 1 charlie charlie      512 Jul 26 14:17 .
drwxrwxrwx 1 charlie charlie      512 Jul 26 14:17 ..
-rwxrwxrwx 1 charlie charlie 12432065 Jul 26 14:17 about.zip
-rwxrwxrwx 1 charlie charlie    41650 Jul 26 14:17 cloudformation-template-update-stack.json
-rwxrwxrwx 1 charlie charlie 13073721 Jul 26 14:17 form.zip
-rwxrwxrwx 1 charlie charlie 17798666 Jul 26 14:17 githubWebhook.zip
-rwxrwxrwx 1 charlie charlie 13015038 Jul 26 14:17 releaseLog.zip
-rwxrwxrwx 1 charlie charlie    59616 Jul 26 14:17 serverless-state.json
-rwxrwxrwx 1 charlie charlie 12446684 Jul 26 14:17 status.zip
```

**Comment by Limess** [comment]
I'd merge this but I don't know how to test it on test...

**Comment by Limess** [comment]
Dora:
>  please hold fire on the source map support, there was a gotcha on individual packaging but serverless-webpack might have patched it by now, I shall check

Me:
> dya have a link to the serverless-webpack issue? (edited)

Dora:
> not specifically, i remember running into similar issues with includes & excludes https://github.com/serverless/serverless/issues/5329
> merging to master would deploy to test and not break anything so let's give that a go with package: / individually: / true

**Pull request merged**
